### ISSUE TITLE
Makefile Missing

### ISSUE THREAD

**Issue by R-I-S-Khan** [RedisLabs/memtier_benchmark#125]
The updated new version does not seem to have the Makefile for running make command that is present in the README.
`
$ make
`
`
make: *** No targets specified and no makefile found.  Stop
`

**Comment by yossigo** [comment]
@R-I-S-Khan memtier_benchmark uses GNU autotools to generate a Makefile dynamically. To build, you need these tools installed (autoconf, automake, libtool, pkg-config) and execute these steps:

To generate the autoconf configure script:
```
autoreconf -ivf
```

To use the configure script to generate Makefiles and such:
```
./configure
```

Please refer to the README for more information.

**Comment by R-I-S-Khan** [comment]
I am running a EC2 t2-micro instance with Amazon Linux 2. 

I followed the steps in README for Centos. In the section Building and Installing when I entered the memtier-benchmark directory after cloning the repository I used the autoreconf -ivf command. Afterwards, I used the ./configure command. But there was "No package 'libevent_openssl' found" error. So I ran 
`
 $ sudo yum install libevent libevent-devel
`
`
 $ sudo yum install openssl-devel
`
 Then when I ran ./configure, all things went well. Except there was line that was displayed as 'no'
`
checking for gai_strerror in -lsocket... no
`
Afterwards, when I ran the make command, I got an error.

`
[ec2-user@ip-xxx-xx-xx-xxx memtier_benchmark]$ make
make  all-am
make[1]: Entering directory `/home/ec2-user/memtier_benchmark'
  CXX      memtier_benchmark-memtier_benchmark.o
  CXX      memtier_benchmark-client.o
  CXX      memtier_benchmark-cluster_client.o
  CXX      memtier_benchmark-shard_connection.o
shard_connection.cpp: In member function ‘void shard_connection::setup_event(int)’:
shard_connection.cpp:196:17: error: ‘bufferevent_openssl_socket_new’ was not declared in this scope
         m_bev = bufferevent_openssl_socket_new(m_event_base,
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
shard_connection.cpp:196:17: note: suggested alternative: ‘bufferevent_socket_new’
         m_bev = bufferevent_openssl_socket_new(m_event_base,
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 bufferevent_socket_new
shard_connection.cpp: In member function ‘void shard_connection::handle_event(short int)’:
shard_connection.cpp:511:26: error: ‘bufferevent_get_openssl_error’ was not declared in this scope
         while ((sslerr = bufferevent_get_openssl_error(m_bev))) {
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
shard_connection.cpp:511:26: note: suggested alternative: ‘bufferevent_get_enabled’
         while ((sslerr = bufferevent_get_openssl_error(m_bev))) {
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                          bufferevent_get_enabled
make[1]: *** [memtier_benchmark-shard_connection.o] Error 1
make[1]: Leaving directory `/home/ec2-user/memtier_benchmark'
make: *** [all] Error 2
`
Do you or anyone have any ideas on how to solve this error in makefile?

**Comment by yossigo** [comment]
Try to uninstall `libevent` and install `libevent2-devel`.

**Comment by R-I-S-Khan** [comment]
@yossigo 
I removed both libevent and libevent-devel and then tried to install both libevent2 and libevent2-devel.
But, I get an error which says that there are no packages like libevent2 or libevent2-devel.

**Comment by yossigo** [comment]
@R-I-S-Khan You are right, `libevent` on Amazon Linux 2 is already version 2.x and apparently it is bundled with the openssl module as well. I can confirm it builds as expected on this platform, I suggest to start from scratch on a newly checked out repo and after installing the necessary packags.

**Comment by R-I-S-Khan** [comment]
@yossigo 

Hi, I am now running trying to run the make command inside the memtier_benchmark in a fresh CentOS 7 local system [not Amazon Linux]. But there is still an error. I am not sure what is causing this. I followed the steps mentioned in the README exactly. However, README.md mentions CentOS 6.x . I am not sure whether there is something that needs to be done additionally for CentOS 7.

![make_error2](https://user-images.githubusercontent.com/28854577/83083835-3203de00-a055-11ea-8da1-3144cb09a4fc.PNG)

**Comment by yossigo** [comment]
@R-I-S-Khan Did you install the `libevent-devel` package provided by CentOS or did you install your own? Seems to build cleanly for me on a fresh CentOS docker image using the CentOS-provided package.

**Comment by yossigo** [comment]
@R-I-S-Khan I assume this has been solved, if not please feel free to respond and re-open the issue.
