### ISSUE TITLE
'All Stats' output contains zeros for all the columns except 'Latency'

### ISSUE THREAD

**Issue by speddam** [RedisLabs/memtier_benchmark#128]
Hi,

The latest memtier_benchmark shows the 'All Stats' output containing all zeros for all the columns except 'Latency', like this:

    $ ./memtier_benchmark --clients=50 --threads=4 --requests=10000 --data-size-range=32-1000 --pipeline=100 --ratio=5:5
    ...
    ALL STATS
    =========================================================================
    Type         Ops/sec     Hits/sec   Misses/sec      Latency       KB/sec 
    -------------------------------------------------------------------------
    Sets            0.00          ---          ---     19.71200         0.00 
    Gets            0.00         0.00         0.00     19.73500         0.00 
    Waits           0.00          ---          ---      0.00000          --- 
    Totals          0.00         0.00         0.00     19.72300         0.00
    ...

I have done the git bisect and it pointed to this commit [0]:

    $ git bisect bad
    bec9cc46079476c8414ab7104516c5a9c966b90f is the first bad commit
    commit bec9cc46079476c8414ab7104516c5a9c966b90f
    Author: YaacovHazan <31382944+YaacovHazan@users.noreply.github.com>
    Date:   Wed Dec 11 17:02:15 2019 +0200

        fix issue #94 cluster mode stuck (#106)
    
        add missing bufferevent_disable for connections that
        complete to send new requests

    :100644 100644 b9fe31c3568e172369897c0eea0111138dcc5e8b 6fbcd856130c8709f8786c97e6b38ad101ca342c M	shard_connection.cpp

I'm not familiar with the code base, but by commenting out the bufferevent_disable() call, I see that the output now shows all the columns:

    ALL STATS
    =========================================================================
    Type         Ops/sec     Hits/sec   Misses/sec      Latency       KB/sec 
    -------------------------------------------------------------------------
    Sets       509744.79          ---          ---     19.52900    281230.68 
    Gets       509744.79       509.74    509235.05     19.53200     20145.57 
    Waits           0.00          ---          ---      0.00000          --- 
    Totals    1019489.58       509.74    509235.05     19.53000    301376.25

---

   Regards,
   Subhash

[0] https://github.com/RedisLabs/memtier_benchmark/commit/bec9cc46079476c8414ab7104516c5a9c966b90f?diff=unified#commitcomment-38744660

**Comment by rohitjoshi** [comment]
I have the same issue and by commenting out the line, it works fine.

```
@@ -473,7 +473,7 @@ void shard_connection::fill_pipeline(void)
         if (m_conns_manager->hold_pipeline(m_id)) {
             // if we are still connected, disable any event
             if (get_connection_state() == conn_connected) {
-                bufferevent_disable(m_bev, EV_WRITE|EV_READ);
+                //bufferevent_disable(m_bev, EV_WRITE|EV_READ);
             }

             break;
```

**Comment by yaacovhazan-Redislabs** [comment]
thank you @speddam and @rohitjoshi for raising the issue and narrow it to the specific line where the issue started... I created PR #130, that should fix it.

**Comment by yossigo** [comment]
Closing this as I assume it's fixed, please re-open if you still experience a problem.

**Comment by godjoem** [comment]
Hi, I have a similar issue when running memtier_benchmark in cluster mode.
The command I run:
```
memtier_benchmark -s 127.0.0.1 -p 6380 -c 50 -n 10000 --cluster-mode \
  --key-prefix={account}: --key-minimum=1 --key-maximum=10000 \
  --command='EVAL "redis.log(redis.LOG_NOTICE, \"Processing account_key: \" .. KEYS[1]); local account_key = KEYS[1]; local min_amount = tonumber(ARGV[1]); local max_amount = tonumber(ARGV[2]); local amount = math.random(min_amount, max_amount); local current_balance = redis.call(\"HGET\", account_key, \"balance\"); if not current_balance then return {err = \"Account not found\" .. KEYS[1]} end; current_balance = tonumber(current_balance); local new_balance = current_balance + amount; redis.call(\"HSET\", account_key, \"balance\", new_balance); redis.call(\"LPUSH\", \"{account}:transactions\", account_key .. \":\" .. amount); return new_balance" 1 __key__ -100 100' \
  --command-key-pattern=P
```
Output:
```
ALL STATS
============================================================================================================================
Type         Ops/sec    MOVED/sec      ASK/sec    Avg. Latency     p50 Latency     p99 Latency    p100 Latency       KB/sec 
----------------------------------------------------------------------------------------------------------------------------
Evals           0.00         0.00         0.00         3.86523         3.37500        10.81500        16.31900         0.00 
Totals          0.00         0.00         0.00         3.86523         3.37500        10.81500        16.31900         0.00 
```
I use memtier_benchmark 2.1.1 and run Redis cluster in docker containers (latest Redis image).

The output is fine when running the command **speddam** uses
`memtier_benchmark --clients=50 --threads=4 --requests=10000 --data-size-range=32-1000 --pipeline=100 --ratio=5:5 -p 6380 --cluster-mode`
