### ISSUE TITLE
build error in Ubuntu 1510

### ISSUE THREAD

**Issue by simonxiaoss** [RedisLabs/memtier_benchmark#13]
root@simon-d14-1:~/benchmark/memtier_benchmark-1.2.7# ./configure
................
checking for gai_strerror in -lsocket... no
./configure: line 5344: syntax error near unexpected token `LIBEVENT,'
./configure: line 5344: `PKG_CHECK_MODULES(LIBEVENT,'

root@simon-d14-1:~/benchmark/memtier_benchmark-1.2.7# cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.10

**Comment by yossigo** [comment]
@simonxiaoss Looks like autoconf doesn't have pkg-config support, make sure you have the `pkg-config` package installed.

**Comment by simonxiaoss** [comment]
Thanks. Yes, I missed the pkg-config package.
