### ISSUE TITLE
Error: Failed to load certificate file.

### ISSUE THREAD

**Issue by anandxmj** [RedisLabs/memtier_benchmark#142]
I have all certificate files in the current directory and I am running memtier with docker image as command:

docker run --rm redislabs/memtier_benchmark:latest --server myredis-server  --port myredis_port --tls --cert cl.crt  --key cl.key  --cacert ca.crt --clients 1

I got the following error:

139855036176192:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:290:fopen('cl.crt','r')
139855036176192:error:20074002:BIO routines:file_ctrl:system lib:../crypto/bio/bss_file.c:292:
139855036176192:error:140AD002:SSL routines:SSL_CTX_use_certificate_file:system lib:../ssl/ssl_rsa.c:390:
Error: Failed to load certificate file.

**Comment by yossigo** [comment]
Your docker container does not have access to local files unless you bind mount. You can do something like this:

```
docker run  -v $PWD:/workdir--rm redislabs/memtier_benchmark:latest --server myredis-server --port myredis_port --tls --cert c/workdir/l.crt --key /workdir/cl.key --cacert /workdir/ca.crt --clients 1
```

**Comment by anandxmj** [comment]
You are absolutely right and pardon my newbie to docker !

Anand
