### ISSUE TITLE
Error in --cluster-mode option

### ISSUE THREAD

**Issue by AshishVarshneyy** [RedisLabs/memtier_benchmark#148]
Getting an error while using cluster-mode 
 
memtier_benchmark --cluster-mode --data-import=upload.csv
Reading keys from upload.csv... 1290845 keys read.
Writing results to stdout
[RUN #1] Preparing benchmark client...
[RUN #1] Launching threads now...
memtier_benchmark: obj_gen.cpp:442: const char* object_generator::get_value(long long unsigned int, unsigned int*): Assertion `0' failed.
memtier_benchmark: obj_gen.cpp:442: const char* object_generator::get_value(long long unsigned int, unsigned int*): Assertion `0' failed.
memtier_benchmark: obj_gen.cpp:442: const char* object_generator::get_value(long long unsigned int, unsigned int*): Assertion `0' failed.
memtier_benchmark: obj_gen.cpp:442: const char* object_generator::get_value(long long unsigned int, unsigned int*): Assertion `0' failed.
Aborted (core dumped)

**Comment by yossigo** [comment]
@AshishVarshneyy Was this a result of a corrupted data, as you indicated in the other PR?

**Comment by AshishVarshneyy** [comment]
@yossigo no data is not corrupted.
Ya I understood that --cluster-mode is currently not supported as u mentioned in other PR.
Can u plz suggest me alternative way to test load in cluster mode.

**Comment by yaacovhazan-Redislabs** [comment]
@AshishVarshneyy, does populate DB can work? what I mean is that you will do one run of memtier-benchmark just using SET (--ratio=1:0) to populate the DB with keys.
and the other runs to do the benchmark itself, what do you think?

**Comment by AshishVarshneyy** [comment]
@yaacovhazan-Redislabs tried that method but nothing works with cluster-mode.
Suppose I have 6 machines and I have to push keys in all the machine but without cluster-mode, I am unable to push keys in all the machine, keys get updated only in single machine.

**Comment by yaacovhazan-Redislabs** [comment]
@AshishVarshneyy not sure I understood, the 6 machines are your cluster? .. and didn't you succeed to populate using cluster-mode? please share the command line that you executed.

**Comment by AshishVarshneyy** [comment]
root@sjc-rediscluster-1:/home/memtier_benchmark# /home/memtier_benchmark/memtier_benchmark --ratio=1:0 --cluster-mode --data-import=upload.csv
Reading keys from upload.csv... 1290845 keys read.
Writing results to stdout
[RUN #1] Preparing benchmark client...
[RUN #1] Launching threads now...
memtier_benchmark: obj_gen.cpp:442: const char* object_generator::get_value(long long unsigned int, unsigned int*): Assertion `0' failed.
Aborted (core dumped)


but when I tried without cluster-mode it works well but all the keys updated only in one machine not all the machines of cluster.

**Comment by AshishVarshneyy** [comment]
and I have to test load performance in cluster-mode

**Comment by yaacovhazan-Redislabs** [comment]
@AshishVarshneyy, maybe I didn't explain myself well.
what I meant is that you will not use the --data-import option, and let memtier-benchmark to generate the keys. is it something that can work for you?

**Comment by AshishVarshneyy** [comment]
@yaacovhazan-Redislabs Thanks, I tried and it works well but I want to use real data that I have and then test load performances.
