### ISSUE TITLE
doesn't return an error code if can't run

### ISSUE THREAD

**Issue by sjpotter** [RedisLabs/memtier_benchmark#150]
I was testing memtier benchmark with acl's and giving it a user who didn't have permission to do much of anything with the database, but while it outputted those failures that it couldn't do anything with the database, it exited with a 0 value, as if it succeeded.

**Comment by YaacovHazan** [comment]
@sjpotter today memtier-benchmark doesn't handle errors, and from his POV it succeeded (recognized the error and report it).
