### ISSUE TITLE
custom commands ( --command ) add new ability 

### ISSUE THREAD

**Issue by borislitvinov** [RedisLabs/memtier_benchmark#152]
Is it passable to add following functionality:
I want to be able to send a bunch of related redis `commands. 

For example:
--command "SET __key__  __dict__"  will set a random key, value, but if i want to send EXPIRE or INCR to this key , i can't do it.

**Comment by YaacovHazan** [comment]
Thank you @borislitvinov for open this issue.
If I understand correctly, you do want to use random (and not fixed) keys, but have the ability to send other sets of commands to that random key.
can you explain more about your usage? how would you like to see that feature?
for ex', do you mean that all the following `--command` after the `--command "SET key dict"` will go to the last randomized key?

**Comment by borislitvinov** [comment]
Hi @YaacovHazan Yes it is exactly the purpose of this feature. 

The usage may be as following
Let say i want to write some script  for eviction testing.
Passable scenario:
Fill DB with random data -> Set eviction policy "volatile" -> Start populate DB with Hash, STR, Streams -> during population execute test.
As a solution i though about ability of "--command" to get not just str but a kind of pattern ( dict ). 
{ HSET key val , EXP key <rand time>, INCR ,} each of those commands will be executed on the same key. 
This way will help us easily to create a various data patterns

**Comment by YaacovHazan** [comment]
Done, `--command` added to send arbitrary commands
