### ISSUE TITLE
Gaussian Distribution --key-pattern=G:G Stall the Memcached on MacOS

### ISSUE THREAD

**Issue by QingchenDang** [RedisLabs/memtier_benchmark#158]
Hi, I encountered an issue when running memtier_benchmark on my MacOS. It shows the following results. It works well without specifying the key pattern to G:G, and the problem seems not exist in my Ubuntu server.

Could you help resolve the issue?

`$ memtier_benchmark -p 11211 -P memcache_text --key-pattern=G:G`

`Writing results to stdout`
`[RUN #1] Preparing benchmark client...`
`[RUN #1] Launching threads now...`
`[RUN #1 0%,   0 secs]  4 threads:           0 ops,       0 (avg:       0[RUN #1 0%,   0 secs]  4 threads:           0 ops,       0 (avg:       0)`
`[RUN #1 0%,   0 secs]  4 threads:           0 ops,       0 (avg:       0[RUN #1 0%,   0 secs]  4 threads:           0 ops,       0 (avg:       0)`
`[RUN #1 0%,   0 secs]  4 threads:           0 ops,       0 (avg:       0[RUN #1 0%,   0 secs]  4 threads:           0 ops,       0 (avg:       0)`

Thank you very much for helping.

**Comment by YaacovHazan** [comment]
@QingchenDang thank you for opening this issue, I prepared a PR (fix issue #158, gaussian key-pattern on MAC OS) that should fix it.

**Comment by filipecosta90** [comment]
Closing as per #159 fix
