### ISSUE TITLE
when I make && make install , I got error 

### ISSUE THREAD

**Issue by kunwl123456** [RedisLabs/memtier_benchmark#161]
//error detail:
error:
[root@redis memtier_benchmark]# make
make  all-am
make[1]: 进入目录“/env/memtier_benchmark”
  CXX      memtier_benchmark-shard_connection.o
shard_connection.cpp: 在成员函数‘void shard_connection::setup_event(int)’中:
shard_connection.cpp:198:79: 错误：‘bufferevent_openssl_socket_new’在此作用域中尚未声明
                 sockfd, ctx, BUFFEREVENT_SSL_CONNECTING, BEV_OPT_CLOSE_ON_FREE);
                                                                               ^
shard_connection.cpp: 在成员函数‘void shard_connection::handle_event(short int)’中:
shard_connection.cpp:518:61: 错误：‘bufferevent_get_openssl_error’在此作用域中尚未声明
         while ((sslerr = bufferevent_get_openssl_error(m_bev))) {
                                                             ^
make[1]: *** [memtier_benchmark-shard_connection.o] 错误 1
make[1]: 离开目录“/env/memtier_benchmark”
make: *** [all] 错误 2

//os
os:centos 7

//the install of openssl is succeful , I can check the version of openssl :
[root@redis memtier_benchmark]# openssl version -a
OpenSSL 1.0.2k-fips  26 Jan 2017
built on: reproducible build, date unspecified
platform: linux-x86_64
options:  bn(64,64) md2(int) rc4(16x,int) des(idx,cisc,16,int) idea(int) blowfish(idx) 
compiler: gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DKRB5_MIT -m64 -DL_ENDIAN -Wall -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -Wa,--noexecstack -DPURIFY -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/etc/pki/tls"
engines:  rdrand dynamic 

//my install step 
yum install -y autoconf
yum install -y automake
yum install -y make
yum install -y gcc-c++
yum install -y git

yum install -y pcre-devel
yum install -y zlib-devel
yum install -y libmemcached-devel
yum install -y openssl-devel

yum install -y libevent-devel

git clone https://github.com/RedisLabs/memtier_benchmark.git
cd memtier_benchmark
autoreconf -ivf
./configure
make

**Comment by yossigo** [comment]
Looks like your libevent is not configured with SSL support, which is strange because `libevent-devel` should handle this properly. Make sure you don't also have some custom-installed libevent header files anywhere.
