### ISSUE TITLE
Generating value buffer randomly looks like wrong

### ISSUE THREAD

**Issue by caipengbo** [RedisLabs/memtier_benchmark#171]
I took a look at the random value generation code and felt something was wrong, `buf2_idx` might index out of bounds:
https://github.com/RedisLabs/memtier_benchmark/blob/01f3b1a1c59ef84040947ecb3e983ff231398b9f/obj_gen.cpp#L242-L266

**Comment by YaacovHazan** [comment]
@caipengbo thanks. you are right. do you want to open a PR with a solution?

**Comment by caipengbo** [comment]
Yes, I'm interested in it. I'll fix it as soon as possible.

**Comment by caipengbo** [comment]
Do you know why `memtier-benchmark` used this method to generate random buffers?  What is its real intention?
Why use two temporary buffers(`buf1` and `buf2`)? @YaacovHazan

**Comment by YaacovHazan** [comment]
@caipengbo this buffer is used for the `--random-data` option, to generate random data (value) for the commands that `memtier-benchmark` sent. I assume that it use two buffers (`buf1 ^ buf2 ^ Iter`) to maximize the randomization

**Comment by caipengbo** [comment]
I guess it's also intended to maximize randomization and reduce the number of times read the `/dev/urandom` file.
