### ISSUE TITLE
How to specify the field num of hash type

### ISSUE THREAD

**Issue by applehuhu** [RedisLabs/memtier_benchmark#177]
--command "hset __key__ __key__ __data__" -c 20 --threads 5 --key-minimum 1 --key-maximum 10 --data-size 64 -n 100000
this will generate 10 keys and every key has 10 fields.
if need generate 10 keys and every key has 10000 fields，how to set the command?

**Comment by YaacovHazan** [comment]
@applehuhu currently `memtier-benchmark` doesn't support the option to control the number of keys and fields separately.
The option that I see is to add 10 `--command` with hard coded keys and let the `memtier-benchmark` to generate only the fields.
For ex: `--command "hset key1 __key__ __data__" --command "hset key2 __key__ __data__" ...` where the keys are between 1 to 10000

**Comment by applehuhu** [comment]
@YaacovHazan i got it,thx. and another question:
--command "sadd  __key__  __data__" -c 10 --threads 10 --key-minimum 1 --key-maximum 1000 --data-size 64 -R -n 100000 --key-prefix test
this command i think it will generate 1000 key and 10000 elements in every set , actually  generate  about 7000 elements.so ,what is the working mechanism of ’-R‘?

**Comment by YaacovHazan** [comment]
@applehuhu, I'm not sure I got your Q, but in general, even when using randomized data, some of the values ​​will be repeated statistically.
