### ISSUE TITLE
Cannot run with more than 1 client and 1 thread in kubernetes pod

### ISSUE THREAD

**Issue by ric-sec** [RedisLabs/memtier_benchmark#180]
It's not possible to run the memtier_benchmark command with more than 1 thread and 1 client in a docker container.

Getting the following error when running `memtier_benchmark -t 2 -c 1 ...`:
 Json file results.json created...
Writing results to stdout
[RUN #1] Preparing benchmark client...
Connection error: Network is unreachable
connect failed, error = Network is unreachable
prepare: failed to connect, test aborted.
error: failed to prepare thread 1 for test.
command terminated with exit code 1

When running `memtier_benchmark -t 1 -c 1 ...`, it's working fine.

Edit: This does work with the latest version but not with the edge version.
Commit 18d26464e86f59d7aff5a2d0a674af192c8dfa5a seems to work

**Comment by yossigo** [comment]
@ric-sec This seems to be a specific issue with your docker or server environment, not an issue with `memtier_benchmark` itself or its docker image.

**Comment by filipecosta90** [comment]
@ric-sec as @yossigo mentioned it seems you're not properly passing the connection details to memtier and, as expect, it's not able to connect to the redis server(s). 
Closing this issue given is solved by properly passing the connection params. 
example:
```
Connection and General Options:
  -s, --server=ADDR              Server address (default: localhost)
  -p, --port=PORT                Server port (default: 6379)
```
