### ISSUE TITLE
Benchmark azure redis over ssl port 6380

### ISSUE THREAD

**Issue by ric-sec** [RedisLabs/memtier_benchmark#181]
Is it possible to benchmark an azure redis instance over ssl on port 6380?

**Comment by yossigo** [comment]
It should be possible, `memtier_benchmak` does support SSL.

**Comment by ric-sec** [comment]
Got it working after some more trial and error:

memtier_benchmark -t 5 -c 10 -a mypassword -s myredis.redis.cache.windows.net -p 6380 --tls --tls-skip-verify
