### ISSUE TITLE
Question about concurrency within the setting of pipeline

### ISSUE THREAD

**Issue by douxiaoniu77** [RedisLabs/memtier_benchmark#195]
Hello, Would anyone one help me on the question? about the concurrency, that
threads=10
clients=10
pipeline=20

Is the concurrency 100？ Actually with the setting of pipeline, the performance results is better, but how could we calculate the concurrency？?

**Comment by filipecosta90** [comment]
hi there @douxiaoniu77 , the total concurrency will be 100 connections to the DB ( 10 threads, each with 10 clients ). 
WRT pipelining it improves performance by issuing multiple commands at once without waiting for the response to each individual command. All details in https://redis.io/docs/manual/pipelining/

**Comment by douxiaoniu77** [comment]
> hi there @douxiaoniu77 , the total concurrency will be 100 connections to the DB ( 10 threads, each with 10 clients ). WRT pipelining it improves performance by issuing multiple commands at once without waiting for the response to each individual command. All details in https://redis.io/docs/manual/pipelining/
> 
> Feel free to reopen the issue if there are still doubts to be answered.

Many thanks for your reply! It is clear to me now.
Could you please help me on another question?  that when  the ratio of set and get is set as 1:3, or 1:5 (anyway it is not 1:1) with random-data，  I could alway see there is some misses records of Get， is that expected? In another word,  all the data that memtier_benchmark get is picked from the setting data of memtier? Or the setting data is independent from the getting data？
