### ISSUE TITLE
What does the "$1024" stand for  in the debug output of "shard_connection.cpp:442: server xxxxx: handled response (first line): $1024, 1 hits, 0 misses".

### ISSUE THREAD

**Issue by jiajinjinkui** [RedisLabs/memtier_benchmark#198]
When i used memtier_benchbark to do the get data test, i used the --debug option, and  therer is many  "shard_connection.cpp:442: server xxxxx: handled response (first line): $1024, 1 hits, 0 misses" output , can you help to confirm what does $1024 stand for？Thank you in advance!
if it stand for get data size but my test command is to get 4 bytes why it reponse 1024 bytes?
 
**Below is the test command:**
memtier_benchmark -s xxxxxx -p xxx -n 50000 -c 10 -t 10 --ratio=0:10 --pipeline=1 -R --key-minimum=1 --key-maximum=5000000 --key-pattern=P:P --debug -d 4 --show-config
**Below is the output:**
![image](https://user-images.githubusercontent.com/61533994/209142815-6a99deb1-0ce7-484b-81c1-b91b6add04da.png)

**Comment by YaacovHazan** [comment]
Hi @jiajinjinkui, the `$1024` is indeed the size of the data for the GET command (The `$` is a bulk string reply).
The `-d  --data-size` is the size for data that memtier-benchmark generates for requests like SET command (In GET command memtier-benchmark doesn't generate any data and just returns whatever is in the DB).
To test GETs with 4 bytes data size, first, you need to populate the DB with keys in that size.

**Comment by jiajinjinkui** [comment]
Hi YaacovHazan, thanks for your confirmation and advise. But there is one parameter --data-offset=OFFSET(Actual size of value will be data-size + data-offset. Will use **SETRANGE / GETRANGE** (default: 0)) which default value is zero, so i think "-d 4" test will get the front 4 bytes, but actually it is not.
I also used setrange and getrange command in the redis client, the two command can get or set any value in the key, but when i used --data-offset and --data-size int the memtier-benchmark test, can not get what i expect. Now i can only used below command to test "get 4 size test" and indeed the debug out is $4, but not sure if the test method is make sense or i should  to populate the DB with keys in test size .
memtier_benchmark -s xxxxxxx -p xxxx -n 30000 -c 50 -t 32 --ratio=0:10 -R --key-minimum=1 --key-maximum=8000000 --key-pattern=P:P **--data-offset=1020 -d 4**
The key value in the DB is 1024 bytes; i change --data-offset value to other number, it will get the size bebind it, the --data-size setting not effect.
![image](https://user-images.githubusercontent.com/61533994/209462073-b08b9378-2bce-4f88-8ccf-d591cd7f617b.png)

**Comment by YaacovHazan** [comment]
@jiajinjinkui the `--data-size` has no effect on either GET or GETRANGE (when using `--data-ofset`).
When using the `--data-offset` the GETRANGE returns the size between the offset to the end of the string.
Not sure what is your goal in the test, but assuming 1024 bytes keys, using  `--data-offset 1020` will return 4 bytes reply (no need/effect of using `--data-size` argument) but with GETRANGE command and not GET (if it matters in some way)

**Comment by jiajinjinkui** [comment]
@YaacovHazan The purpose of my test is to simplify the testing process, for example if i want to test "get 4" "get 32" "get 1024" three types test i only need to  set 1024 one times and then used --data-offset parameter to test "get 4" "get 32" "get 1024" no need to do "set 4" and "set 32". Your reply solved my problem, thanks a lot. Below is the sample used --data-offset and --data-size to test on redis website . https://redis.com/blog/new-in-memtier_benchmark-pseudo-random-data-gaussian-access-pattern-and-range-manipulation/
![image](https://user-images.githubusercontent.com/61533994/210472398-815fe7ad-b9c9-4f21-ac26-8878ef424e40.png)

**Comment by YaacovHazan** [comment]
@jiajinjinkui, glad to here that it solved your problem. Can we close the issue please?
