### ISSUE TITLE
CLUSTERDOWN: hash slot not served response from node not part of cluster

### ISSUE THREAD

**Issue by shailymittal** [RedisLabs/memtier_benchmark#231]
I ran memtier benchmark on a redis cluster
Some details about the benchmark
1. Commands - set:get commands
2. Key types - string
3. Wait commands - no

During the benchmark, one of the Master node in the cluster failed over and was removed from the cluster and I started getting below error
-CLUSTERDOWN: hash slot not served
error from the cluster even though at the time this node was not part of not cluster for every "CLUSTER INFO" command was returning "I am no longer part of any cluster"

@YaacovHazan : could you help with this?

**Comment by YaacovHazan** [comment]
Hi @shailymittal . IIUC, once one of the Master nodes failed over and was removed from the Cluster, you lost full slot range coverage and started getting the `-CLUSTERDOWN: hash slot not served`

A few Q's:
1. From where did you get the `I am no longer part of any cluster` error? It isn't a Redis response (at least not the OSS Redis).
2. Why are you asking about `blocking command`? How blocking command related to the issue?
