### ISSUE TITLE
Error reported when running with "--data-import"

### ISSUE THREAD

**Issue by DarrenJiang13** [RedisLabs/memtier_benchmark#238]
# Problem
Hi guys, when I run the newest master branch with "--data-import", an error happened:
```
memtier_benchmark: obj_gen.cpp:438: const char* object_generator::get_value(long long unsigned int, unsigned int*): Assertion `0' failed.
```

And I found this is brought by commit https://github.com/RedisLabs/memtier_benchmark/commit/1c6735f06d5fe63a55b671860baf7b858de5551b , before this commit "--data-import" worked OK.

# Discussion
IMHO the problem should be in `client::create_set_request()`.  I change it like this and things go right. But I am not sure this is the right solution
![image](https://github.com/RedisLabs/memtier_benchmark/assets/29703715/ad10cc4d-ccdc-483d-b5ff-b17f88c42294)

**Comment by YaacovHazan** [comment]
@DarrenJiang13 , thanks for reporting this bug.
You are right, the `--data-import` broke by commit https://github.com/RedisLabs/memtier_benchmark/commit/1c6735f06d5fe63a55b671860baf7b858de5551b, but unfortunately the fixed is not that simple.

I will work on a fix and update.
