### ISSUE TITLE
memtier benchmark doest resolve the new DB host ID on a node failure

### ISSUE THREAD

**Issue by dragnot** [RedisLabs/memtier_benchmark#26]
the test is like this. 

run memtier on redis pack DB with replication with default endpoint bind.  
kill endpoint and master redis node, failover of endpoint works well and slave is promoted well.  memtier, even if memtier does multiple run ( using -x parameters ) it will never connect to the new endpoint. 

restart memtier works and connect correctly. it will be great if memtier can refresh its connection to the new endpoint automatically.

**Comment by yossigo** [comment]
Inactive, closing.

For future reference, `memtier_benchmark` can handle failovers when using cluster-mode with a Redis cluster. However, it does not support neither Sentinel nor any other failover mechanism that depends on repeatedly attempting DNS resolution before a reconnect.
