### ISSUE TITLE
[Bug] Output file sometimes reports 0 for Ops/sec, latency, etc, in the Totals section (even though traffic occurred)

### ISSUE THREAD

**Issue by DrEsteban** [RedisLabs/memtier_benchmark#274]
This seems to happen more often on higher connection count tests, but we've seen it occasionally on lower connection counts as well.

This may be related to #271, and resolved by #273, but logging it as a separate issue just in case!

Example output file: 
[test-run-upload.json](https://github.com/user-attachments/files/17699723/test-run-upload.json)

@filipecosta90

**Comment by filipecosta90** [comment]
Fixed by #273
