### ISSUE TITLE
While calling third party rest api in memtier it fails to make a build

### ISSUE THREAD

**Issue by vitthalpadwal** [RedisLabs/memtier_benchmark#31]
I am trying to execute third party rest api from memtier it give below error while making the build
protocol.cpp:40:9: error: ‘SimpleWeb’ does not name a type
 typedef SimpleWeb::Client<SimpleWeb::HTTP> HttpClient;

So I am trying to use client_http.hpp to call rest api . But I am not  able to create its instance.
I have include header file in protocol.cpp and in makefile

**Comment by yossigo** [comment]
Inactive, closing.
