### ISSUE TITLE
Server hangs if implementing a connection queue

### ISSUE THREAD

**Issue by kalsan** [RedisLabs/memtier_benchmark#38]
We've run into an interesting deadlock problem when implementing a middleware between memtier_benchmark and memched for a university project. We are three people with three independent implementations and we all have the same observation _(see bold part below)_, so I'd like to ask you a few questions in order to gain more insights into memtier_benchmark and the deadlock problem.

We are to implement our middleware using a special architecture: a thread should accept connections and put these into a Java `BlockingQueue` that is then processed by a number of worker threads who forward the request to the memcached server and finally reply to memtier_benchmark. There is a simple illustration for this on page 6 on the [Project description](https://www.systems.ethz.ch/sites/default/files/file/asl2017/documents/project20.pdf). We all decided to serve a request from memtier_benchmark and then put the (still open) connection back into the queue.

The following works with any number of worker threads in the middleware. Here I will consider the case with a single worker thread serving memtier_benchmark requests. I use 1 memtier thread having 200 clients and releasing 10 requests of data size 16.

Starting memtier_benchmark. It works fine until it reaches about 95% progress, then everything blocks. Analysis showed that all three implementations block on reading on a connection from memtier_benchmark. **For some reason, memtier_benchmark suddenly doesn't send any data on a given connection any more. _This is the phenomenon we want to understand._**

We have a possible explanation, but it's highly implementation specific for memtier_benchmark. This is why I'm writing this GitHub issue: we hope to get some light into this mystery. Our tentative explanation is as follows:

- Without loss of generality, let's assume has that memtier_benchmark has a single thread sending out requests and that all open connections ("virtual clients") are stored in a queue. Consider 10 connections between memtier_benchmark and our middleware. Both sides (according to our hypothesis) buffer the connections in a queue.
- At time x (after an arbitrary number of requests have been exchanged and both queues are filled with open connections), the following situation appears:
    - Our middleware replies to a request in connection 3, puts it back into the queue and takes from the queue, getting connection 4. It contacts memcached, gets a reply and forwards the reply to the connection 4. It then puts connection 4 back into the queue and takes connection 5 from the queue.
    - memtier_benchmark takes connection 3 from the queue, checks our reply and sends a new request on connection 3. It then puts the connection 3 back into the queue and takes connection 2 out of the queue. It sends a request and waits for the reply.
    - This means that memtier_benchmark is waiting on connection 2 and our middleware is waiting on connection 5, which would effectively result in a benchmark.

We make bold assumptions about memtier_benchmark's internals in this example. Would such a scenario be possible with memtier_benchmark? **Do you have an idea why the read on a connected memtier_benchmark blocks?** Thank you very much in advance, we are thrilled by the problem and looking forward to hear your input.

**Comment by yossigo** [comment]
Hi, just noticed this message - sorry for the late reply, hope this is still somehow relevant. The memtier_benchmark networking implementation is asynchronous, so the condition you describe should not be possible.   However such deadlocks may be possible even solely in your middleware if it does blocking reads on individual connections.

**Comment by kalsan** [comment]
Thanks a lot for your reply :-)
