### ISSUE TITLE
error response

### ISSUE THREAD

**Issue by sunnylou** [RedisLabs/memtier_benchmark#40]
![default](https://user-images.githubusercontent.com/22695791/32311868-d484e042-bfd5-11e7-9a26-28c97cf7efab.png)
What did I do wrong？

**Comment by sunnylou** [comment]
input: memtier_benchmark --protocol redis -x 1 -s 10.37.32.68 -p 6381 --ratio=1:0 -t16 -c4 --key-pattern=R:R --key-minimum=1 --key-maximum=100000000 -n 15000 -d 32768 -D

output:client.cpp:699: handled response (first line): -MOVED 583 10.37.32.66:6381, 0 hits, 1 misses
error response: -MOVED 583 10.37.32.66:6381
error response: -MOVED 7069 10.37.32.68:6382
client.cpp:534: SET key=[memtier-64150979] value_len=32768 expiry=0
client.cpp:699: handled response (first line): -MOVED 11606 10.37.32.67:6381, 0 hits, 1 misses
error response: -MOVED 11606 10.37.32.67:6381
client.cpp:534: SET key=[memtier-38694230] value_len=32768 expiry=0
error response: -MOVED 11600 10.37.32.67:6381
client.cpp:534: SET key=[memtier-40983116] value_len=32768 expiry=0
client.cpp:699: handled response (first line): -MOVED 8671 10.37.32.68:6382, 0 hits, 1 misses
error response: -MOVED 8671 10.37.32.68:6382
client.cpp:534: SET key=[memtier-78861727] value_len=32768 expiry=0
client.cpp:534: SET key=[memtier-62715073] value_len=32768 expiry=0
client.cpp:699: handled response (first line): -MOVED 11097 10.37.32.67:6381, 0 hits, 1 misses
error response: -MOVED 11097 10.37.32.67:6381
client.cpp:534: SET key=[memtier-25027732] value_len=32768 expiry=0
client.cpp:699: handled response (first line): -MOVED 1808 10.37.32.66:6381, 0 hits, 1 misses
error response: -MOVED 1808 10.37.32.66:6381
client.cpp:534: SET key=[memtier-78302541] value_len=32768 expiry=0
client.cpp:699: handled response (first line): -MOVED 4868 10.37.32.66:6381, 0 hits, 1 misses
error response: -MOVED 4868 10.37.32.66:6381
client.cpp:534: SET key=[memtier-23638978] value_len=32768 expiry=0
client.cpp:699: handled response (first line): -MOVED 4868 10.37.32.66:6381, 0 hits, 1 misses
error response: -MOVED 4868 10.37.32.66:6381
client.cpp:534: SET key=[memtier-23638978] value_len=32768 expiry=0
client.cpp:699: handled response (first line): -MOVED 12217 10.37.32.67:6381, 0 hits, 1 misses
error response: -MOVED 12217 10.37.32.67:6381
client.cpp:699: handled response (first line): -MOVED 583 10.37.32.66:6381, 0 hits, 1 misses
error response: -MOVED 583 10.37.32.66:6381
client.cpp:699: handled response (first line): -MOVED 4013 10.37.32.66:6381, 0 hits, 1 misses
error response: -MOVED 4013 10.37.32.66:6381
client.cpp:534: SET key=[memtier-13116700] value_len=32768 expiry=0
client.cpp:534: SET key=[memtier-64150979] value_len=32768 expiry=0



cluster info :# redis-cli -h  127.0.0.1 -p 6381 -c cluster info
cluster_state:ok
cluster_slots_assigned:16384
cluster_slots_ok:16384
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:8
cluster_size:4
cluster_current_epoch:27
cluster_my_epoch:27
cluster_stats_messages_sent:174461
cluster_stats_messages_received:174458


What did I do wrong?

**Comment by sunnylou** [comment]
Cannot be used on the cluster？

**Comment by yaacovhazan-Redislabs** [comment]
@sunnylou we added support for cluster, please use --cluster-mode option
