### ISSUE TITLE
How may I control hit ratios

### ISSUE THREAD

**Issue by ronen-lb** [RedisLabs/memtier_benchmark#41]
I am using memtier_benchmark to verify a private memcashed. 
I would like to verify performance with diffrent loads, such as (70% get/30% read).
ideally with random keys and random values.
However I would like to ensure that hit ratio is 100%, i.e all gets are for keys already set.
How/If can i control this in memtier_benchmark?

**Comment by yossigo** [comment]
As far as I remember there's no way to do exactly that.  Depending on your needs, you may be able to just use a small dataset that will guarantee 100% hit ratio (at least shortly after the test begins).
