### ISSUE TITLE
SSL/TLS support

### ISSUE THREAD

**Issue by slmingol** [RedisLabs/memtier_benchmark#53]
From looking at memtier_benchmark's source code it didn't appear to support TLS/SSL connections to Redis. Are there any plans to implement this?

**Comment by dimakuv** [comment]
+1. Hopefully, Amazon's PR for Redis will be accepted soon (https://github.com/antirez/redis/pull/4855). Would be great to have memtier_benchmark compatible with this version.

**Comment by yaacovhazan-Redislabs** [comment]
@slmingol @dimakuv, thanks for your suggestion.
TLS/SSL support is already one of the top items in our roadmap for memtier_benchmark.

**Comment by yossigo** [comment]
See #90

**Comment by Ilovehome666** [comment]
Anyone know any tool to test memcached or redis with mTLS?
