### ISSUE TITLE
Issues running with mac os

### ISSUE THREAD

**Issue by nithinmohan** [RedisLabs/memtier_benchmark#57]
I am trying to run memtier_benchmark on mac os. My Redis instances are running on my local machine which runs mac os

1. Trying with Docker
Running tests for a single instance(non cluster-mode) works fine after using -net=host. But when using --cluster-mode flag I am getting connection refused error. I guessed it is because CLUSTER SLOTS command will return ip as 127.0.0.1 from my local machine and then memtier uses it inside docker image and fails. To avoid that I set up rerouting of IP 127.0.0.1 to my local machines IP. This seemed working, but Redis started giving error "Error: Connection reset by peer" when using redis-cli from my docker image.
I gave up at this point

2. Building from source file
`./configure` command gives an error at with this log
```
checking for pcre_compile in -lpcre... yes
checking for deflateInit_ in -lz... yes
checking for clock_gettime in -lrt... no
configure: error: rt is required for libevent
```

Can you please point me in the right direction?

**Comment by nithinmohan** [comment]
UPDATE:
I was able to bypass this check by commenting out the following line in configure.ac
`AC_CHECK_LIB([rt], [clock_gettime], , AC_MSG_ERROR([rt is required for libevent.]))`

**Comment by YaacovHazan** [comment]
@nithinmohan, what is the output of CLUSTER  SLOTS command when you run it manually from the docker?

**Comment by yossigo** [comment]
Inactive, closing.
