### ISSUE TITLE
connect: connection failed: Connection timed out

### ISSUE THREAD

**Issue by qunchenmy** [RedisLabs/memtier_benchmark#6]
$  for p in `seq 1 10` ;do  /apps/svr/redis/bin/redis-cli -h 10.201.111.111 -p 6379 -a c4uT62vgCajbnvtgYFbq flushall ;./memtier_benchmark -s 10.201.111.111  -p 6379 -a c4xxxxxxxxxbq -n 10000 -c 16   -t 32  --reconnect-interval=10  | head -n 15 ;done
a lot of 'connect: connection failed: Connection timed out' error information  in benchmark outputs.

**Comment by yossigo** [comment]
Closing as obsolete.
