### ISSUE TITLE
Redis server eats up memory if benchmarking with --run-count

### ISSUE THREAD

**Issue by dimakuv** [RedisLabs/memtier_benchmark#61]
I locally benchmark a Redis server 5.0 with the following command:
`memtier_benchmark --show-config -d 4096 --key-maximum=50000 --hide-histogram -t 8 --ratio=1:1 --key-pattern=P:P --run-count 10`

So, I have 50K keys and values of size 4K. The maximum size of my Redis instance must be `50K*4KB ~= 200MB`.

However,  with each next run of memtier-benchmark, my Redis instance size *increases* by 200MB. After 10 runs, Redis eats `10*200MB = 2GB` of RAM.

I assumed that Redis must replace the same keys and delete old values, so its size is always capped at ~200MB. Why do I see 2GB then? Is this the intended behavior of `--run-count`?

**Comment by yaacovhazan-Redislabs** [comment]
Hi @dimakuv, sorry for the late response and thank you for raising this issue.
you are right, this is a bug, the range of the keys shouldn't be exceeded when using the run-count option.
We will push a fix soon.

**Comment by yossigo** [comment]
Fixed by #62
