### ISSUE TITLE
With `--test-time` option, benchmark doesn't really finish after `test-time` seconds

### ISSUE THREAD

**Issue by dimakuv** [RedisLabs/memtier_benchmark#64]
The `--test-time` option forces memtier_benchmark to finish after `test-time` seconds.

However, I noticed that each client actually waits to receive a reply from a Redis server, then checks if `test-time` elapsed, and then stops. In my case, I have many parallel clients and many stragglers, where a single Redis reply can take several seconds to come back to client.

Thus, even though I specify `--test-time=10`, it takes significantly more than 10 seconds. This not only takes too long for one experiment run, but also skews the results. (Which may be the behavior the authors desired?..)

I believe that all clients must die immediately after `test-time` seconds. I fixed this issue with the following trivial patch:
```C
diff --git a/client.cpp b/client.cpp
index e827195..f074877 100755
--- a/client.cpp
+++ b/client.cpp
@@ -557,7 +557,18 @@ int client_group::prepare(void)

 void client_group::run(void)
 {
+    // exit event loop immediately after test_time seconds
+    if (m_config->test_time > 0) {
+        struct timeval endtime;
+        endtime.tv_sec  = m_config->test_time;
+        endtime.tv_usec = 0;
+        event_base_loopexit(m_base, &endtime);
+    }
+
     event_base_dispatch(m_base);
+
+    for (std::vector<client*>::iterator i = m_clients.begin(); i != m_clients.end(); i++)
+        (*i)->set_end_time();
 }

 unsigned long int client_group::get_total_bytes(void)
```

**Comment by phil9987** [comment]
I agree that this is an annoying problem. Thanks for proposing this solution.

**Comment by yaacovhazan-Redislabs** [comment]
thank you @dimakuv for the proposed solution, we will test it, and if it doesn't introduce any other negative side effects we will merge it.

**Comment by yaacovhazan-Redislabs** [comment]
Thank you @dimakuv for the idea to use event_base_loopexit to end tests where the response can take several seconds to come back to the client.

Although it’s a good idea, we decided not to implement it. It seems to us that most people would prefer to wait for responses before ending the test, and that ending the test before receiving the responses can cause a mismatch between the report of the ops that memtier-banchmark handled and the actual ops that sent and processed by redis-server.
