### ISSUE TITLE
Docker Hub image is outdated

### ISSUE THREAD

**Issue by pataquets** [RedisLabs/memtier_benchmark#69]
https://hub.docker.com/r/redislabs/memtier_benchmark
Current master Dockerfile builds 1.2.15 and Hub's is 1.2.8.
Perhaps setting an Automated Build would be better. It would build always master branch to :latest image tag and would create individual image tags for each additional git tag.
See https://docs.docker.com/docker-hub/builds/

**Comment by pataquets** [comment]
#70 can be used to test Automated Build triggering ;)

**Comment by pataquets** [comment]
@yaacovhazan-Redislabs : ping

**Comment by yaacovhazan-Redislabs** [comment]
@pataquets, thanks. @RoeyPrat will work to update the image on Docker Hub and to review your PR #70

**Comment by itamarhaber** [comment]
@pataquets thanks for reporting this.

I've pushed the latest (1.2.16) the Docker Hub (tagged as :1.2.16 and :latest) and set up automated builds on master (:edge) and future version tags.

Please keep this issue open at least until the next version release so we can verify that it is actually working properly, but for it "should work".

**Comment by itamarhaber** [comment]
Verified that Docker's autobuild works with 1.2.17 - closing.
