### ISSUE TITLE
latency and throughput are not matching?

### ISSUE THREAD

**Issue by qunchenmy** [RedisLabs/memtier_benchmark#7]
the latency and the throughput are not matching.
the machines are  free without any application process.

1) test with no password.  has a  low latency and less throughput

$ for p in `seq 1 10` ;do  /apps/svr/redis/bin/redis-cli -h 10.201.111.111 -p 6379 -a c4uT62vgCajbnvtgYFbq flushall ;./memtier_benchmark -s 10.201.111.111  -p 6379 -a c4uT62vgCajbnvtgYFbq -n 5000 -c 32   -t  4  --reconnect-interval=5  | head -n 10 ;done  
OK
[RUN #1] Preparing benchmark client...
[RUN #1] Launching threads now...
[RUN #1,  10 secs]  0 threads:      640000 ops,   62483 ops/sec, 2.32MB/sec,  0.70msec latency
4         Threads
32        Connections per thread
5000      Requests per thread
Type        Ops/sec     Hits/sec   Misses/sec      Latency       KB/sec
Sets        5689.69          ---          ---      0.70000       438.33
Gets       56834.37         0.00     56834.37      0.69700      1936.84
Totals     62524.06         0.00     56834.37      0.69700      2375.17

2) test with  password  has a  high latency and more throughput

$ for p in `seq 1 10` ;do  /apps/svr/redis/bin/redis-cli -h 10.201.111.111 -p 6379  flushall ;./memtier_benchmark -s 10.201.111.111  -p 6379 -n 5000 -c 32   -t  4  --reconnect-interval=5  | head -n 10 ;done 
OK
[RUN #1] Preparing benchmark client...
[RUN #1] Launching threads now...
[RUN #1,   9 secs]  0 threads:      640000 ops,   69699 ops/sec, 2.59MB/sec,  1.78msec latency
4         Threads
32        Connections per thread
5000      Requests per thread
Type        Ops/sec     Hits/sec   Misses/sec      Latency       KB/sec
Sets        6410.54          ---          ---      1.77800       493.86
Gets       64034.96         0.00     64034.96      1.77500      2182.23
Totals     70445.50         0.00     64034.96      1.77600      2676.09

**Comment by yossigo** [comment]
Old/inactive issue, closing.
