### ISSUE TITLE
Adding data using --data-import

### ISSUE THREAD

**Issue by Upasana2101** [RedisLabs/memtier_benchmark#73]
I generated the file in the same format by referring to yours. Below is an example of the first few entries.

**dumpflags, time, exptime, nbytes, nsuffix, it_flags, clsid, nkey, key, data
0, 0, 0, 200, 200, 0, 1, 200, sqjbmtzgladigkgckqxhqvkvnvcdrctjfqvsfnkwcocgagwvfbsbpadxxirdnkfexzifhmqxriaqvwiwxegholwgheabfqdhvxyqquaoxqrcebhjlvvsurgofgaapmqgyvtngtfkhiowfezfsjsyspzdffaojbwwqombzlvwhqqxdschnjgcjtgfmdxmvpmujreflbvc, ddcihrvrhfykwaprhhoxrgqcgcekmxkfkptrkhsvptkgnxqrazainyabxdkznmsgrpsgyeuxzkdopkpioevdmifibezsdhvglfjfojctdrxwlosunongwfpwrsuklfxrkneovbbhkspbmpsqloczpjzoiumspoxhtrqttsyhbrqgbhmibpdzpkboxrpshnylickresgq
0, 0, 0, 200, 200, 0, 1, 200, voaidlhyacrsxwurfwbdharbcuiotsaabyjhohqrperazwfialssbekpdhjujsfosvqvdtkvdocghakxqfxpbjrlpacixygnforgvpkojbylonzynvnezmhenlkmmerisipveqfrefpmgmnumtwtckdvlklegtcmygibekvktjmikqvobepdrdahcvildjprbgtlowam, fujwzhpvjutlhxycaivguimukkkhtvvkwktbtuhthudapksgynusznwnbaarjjqtdroukejmcgfdjzcerfjbbaoclgattmokezeeooptggpqdwagcltwqhbdnhsyxstxfdsgoemsbnbjyjgtmnklklhvjspsxbcnaffsofxrlxzgjwppdjyaioonzzxbhrsydivfmlkf**

Note : The strings are not separated by newline they are just separated by the comma. There is a newline only after one complete entry

I want to insert these as key value pairs using memcache_text.
I am using the following command:
**memtier_benchmark -p 11211 -P memcache_text -t 4 -n 100 –ratio 1000:0 -c 25 -x 5 --data-import=key.csv**

Note: file name is key.csv 

But I am getting this error-
key.csv:2: error parsing item values.

How to insert these key-value pairs using memtier_benchmark?

**Comment by AshUserr** [comment]
I'm also facing the problem while uploading data in Redis through --data-import option.

**Running:**
docker run -v "$PWD:$PWD" -w "$PWD" --rm --net=host redislabs/memtier_benchmark:latest -t 4 -n 100 –ratio 1:1 --cluster-mode --data-import=data.csv

**CSV file content:**
dumpflags, time, exptime, nbytes, nsuffix, it_flags, clsid, nkey, key, data
0, 0, 0, 200, 200, 0, 1, 11, 'doxrpshny', 'asdfghjklqwertyuiopxcvbnmasdfghjklweioxcvbnmsdfkledjklcvbnmdfgklerpasdfghjklqwertyuiopxcvbnmasdfghjklweioxcvbnmsdfkledbdbfdbffkdbhssksidjbdsdfdsjhgsfsldkfesdnsldnidnskdnsknsjdgiwndsdoqwertyondojfp'

**Error:**
Reading keys from data.csv... 1 keys read.
[RUN #1] Preparing benchmark client...
[RUN #1] Launching threads now...
memtier_benchmark: obj_gen.cpp:438: const char* object_generator::get_value(long long unsigned int, unsigned int*): Assertion `0' failed.
memtier_benchmark: obj_gen.cpp:438: const char* object_generator::get_value(long long unsigned int, unsigned int*): Assertion `0' failed.
memtier_benchmark: obj_gen.cpp:438: const char* object_generator::get_value(long long unsigned int, unsigned int*): Assertion `0' failed.

**Comment by yaacovhazan-Redislabs** [comment]
Hi @Upasana2101, the value of nbytes should include the CRLF, so in your case, if the value is 200 length, you should insert 202 (or delete 2 characters from the value)

**Comment by yaacovhazan-Redislabs** [comment]
@AshUserr, thank you for raising this issue, unfortunately `--data-import` is not supported yet with `--cluster-mode`

**Comment by AshUserr** [comment]
@yaacovhazan-Redislabs 
okay, thanks for the info.
