### ISSUE TITLE
Incorrect throughput in final table

### ISSUE THREAD

**Issue by DaisyHsiung** [RedisLabs/memtier_benchmark#8]
The throughput number(5272.41 KB/sec)  in the final table is incorrect.

 $./memtier_benchmark --protocol redis -x 1 -s 209.243.160.17 -p 6379 --ratio=1:0 -t16 -c4 --key-pattern=R:R --key-minimum=1 --key-maximum=100000000  -n 15000 -d 32768[RUN #1] Preparing benchmark client...
[RUN #1] Launching threads now...
[RUN #1 100%, 266 secs]  0 threads:      960000 ops,    3549 (avg:    3604) ops/sec, 111.09MB/sec (avg: 112.81MB/sec), 18.08 (avg: 17.73) msec latency

16        Threads
4         Connections per thread
15000     Requests per thread
Type        Ops/sec     Hits/sec   Misses/sec      Latency       KB/sec
Sets        3595.90          ---          ---     17.72600      5272.41
Gets           0.00         0.00         0.00      0.00000         0.00
Totals      3595.90         0.00         0.00     17.72600      5272.41

**Comment by itamarhaber** [comment]
@DaisyHsiung this does not reproduce with the latest version. Please verify and close this issue.
