### ISSUE TITLE
Support for multiple memcached servers?

### ISSUE THREAD

**Issue by nikhilk** [RedisLabs/memtier_benchmark#81]
Is it possible to configure the tool to work against a set of memcache servers, rather than being limited to a single one?

**Comment by yaacovhazan-Redislabs** [comment]
hi @nikhilk, currently, memtier-benchmark doesn't support this option.

**Comment by nikhilk** [comment]
Good to know I wasn't missing some existing option based on my read of the help text. Would this be interesting to track as a feature/ask?

**Comment by itamarhaber** [comment]
Hello @nikhilk 

If I understand correctly, by "work against a set of memcache servers" you are referring to the cluster pattern that in MC is implemented entirely client-side. This currently isn't on our roadmap but let's keep this open as a feature request to gather more feedback (and possibly a PR ;)).

**Comment by nikhilk** [comment]
Yes, that is the pattern.

While I personally think its interesting to have a proxy router rather than exposing individual servers in many cases, the reason I was using this benchmarking tool was (somewhat ironically) to compare the performance of a proxy based solution vs. a set of servers exposed to the client.

**Comment by yossigo** [comment]
Duplicate of #15
