### ISSUE TITLE
Use -h --hostname instead (or in addition) to -s to match redis-cli, redis-benchmark...

### ISSUE THREAD

**Issue by tgrall** [RedisLabs/memtier_benchmark#87]
The `memtier_benchmark` tool is using the `-s` `--server` as a parameter to pass the server address.

It would be good to be consistent with other `redis-*` tools and use  `-h` `--hostname` instead

**Comment by filipecosta90** [comment]
Fixes by https://github.com/RedisLabs/memtier_benchmark/pull/224 and released as part of https://github.com/RedisLabs/memtier_benchmark/releases/tag/2.0.0
