### ISSUE TITLE
Setting connect_timeout for memcache

### ISSUE THREAD

**Issue by ruizhang2015** [RedisLabs/memtier_benchmark#93]
Hi,

Thanks for developing and maintaining the great tool!

I was trying this tool with memcached and encountered a lot of "Connection error: Connection timed out". These errors weren't quite surprising to me since my memcached server was instrumented by an intel pintool and thus expected to be very slow when handling connections. So I was wondering if there's any way I can increase the timeout value for the benchmark tool to connect to the server. I figured out there's a libmemcached option "MEMCACHED_BEHAVIOR_CONNECT_TIMEOUT" that seems relevant, but I have no idea how to use it in the benchmark tool.

Any help/thought would be appreciated!

**Comment by yossigo** [comment]
@ruizhang2015 the libmemcached option will not be effective because `memtier_benchmark` handles its own connections.  It should be fairly easy to change the connect timeout, but you'll need to modify `shard_connection.cpp` to do that.

**Comment by ruizhang2015** [comment]
Hi Yossi,

Thanks a lot for pointing out my misunderstanding about using libmemcached!

I looked at shared_connection.cpp and if I understand the code 
correctly, a "connection time out" error is thrown by 
bufferevent_socket_connect() and handled in 
shard_connection::handle_event(). So I'll need to set a large timeout 
value before bufferevent_socket_connect(). I searched online for such a 
setting but have yet to have any luck.

Am I in the right direction? I'd really appreciate it if you could share 
with me a little more about setting connection timeout. :)

Best,
Rui

**Comment by yossigo** [comment]
@ruizhang2015 I had a look a that, apparently there's no timeout enforced there so you may need need to increase retires at the kernel level. How long is the timeout threshold you experience?

**Comment by ruizhang2015** [comment]
> How long is the timeout threshold you experience?

I don't have the exact number at the moment. But I kinda figured out that it's because I was using a 32threads*50clients config. The problem went away after I reduced the client count to 1.
