### ISSUE TITLE
get error "error: response parsing failed"

### ISSUE THREAD

**Issue by 1a1a11a** [RedisLabs/memtier_benchmark#99]
I am trying to work with Memcached, but I get "error: response parsing failed". 
```
protocol.cpp:477: unsupported response: 'ERROR'.
error: response parsing failed.
```

**Comment by itamarhaber** [comment]
Hello @1a1a11a 

Would you be kind enough to provide the steps to reproduce the issue? Specifically, it would be extremely helpful if you could include the exact arguments that you call memtier with as well as any relevant details about the target server (e.g. its version).

**Comment by 1a1a11a** [comment]
Thank you for quick response! here is the command I used 
```./memtier_benchmark -p 12000 --threads=8 --test-time=20 --ratio=0:1
```
and I started a memcached server on the localhost at port 12000, I compiled the Memcached GitHub repo as of today and command to start Memcached is `./memcached -m 20000 -v -p 12000 -t 8`.

**Comment by ericpruitt** [comment]
I have the same problem with memcached 1.5.6 and 1.5.22. I ran memcached on port 11211 with `memcached -m64 -p 11211 -u memcache -l 127.0.0.1 -P /tmp/memcached.pid` and memtier_benchmark compiled from HEAD and executed with `./memtier_benchmark -p 1121`.

**Comment by ericpruitt** [comment]
The issue here is that memtier_benchmark doesn't auto-detect the server type, so you need to specify a memcached test using either `-P memcache_text` or `-P memcache_binary`.

**Comment by martin-g** [comment]
Thank you for the hint, @ericpruitt !
